version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: bugreports
      # MYSQL_USER: root
      # MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Auto-load initial SQL

  django-app:
    build: ./django-app
    volumes:
      - ./django-app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  react-app:
    build: ./react-app
    volumes:
      - ./react-app:/app
    ports:
      - "3000:3000"
    depends_on:
      - django-app

volumes:
  db-data:
