# Generated by Django 4.2.11 on 2024-04-08 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RoleName", models.CharField(max_length=255)),
                ("Permissions", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ProgramName", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FunctionalArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AreaName", models.CharField(max_length=255)),
                (
                    "Program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bughoundapp.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Username", models.CharField(max_length=255, unique=True)),
                ("Password", models.CharField(max_length=255)),
                ("ContactInfo", models.CharField(max_length=255)),
                (
                    "Role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bughoundapp.employeerole",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ReportTypeID", models.IntegerField()),
                ("Severity", models.CharField(max_length=255)),
                ("ProblemSummary", models.TextField()),
                ("ProblemDescription", models.TextField()),
                ("Reproducible", models.BooleanField()),
                ("SuggestedFix", models.TextField()),
                ("ReportedByDate", models.DateField()),
                ("Comments", models.CharField(blank=True, max_length=255, null=True)),
                ("Status", models.CharField(max_length=100)),
                ("Priority", models.CharField(max_length=100)),
                ("Resolution", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "ResolutionVersion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ResolvedByDate", models.DateField(blank=True, null=True)),
                ("TestedByDate", models.DateField(blank=True, null=True)),
                ("TreatedAsDeferred", models.BooleanField()),
                (
                    "AssignedToEmployee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_bugs",
                        to="bughoundapp.employee",
                    ),
                ),
                (
                    "FunctionalArea",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bughoundapp.functionalarea",
                    ),
                ),
                (
                    "Program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bughoundapp.program",
                    ),
                ),
                (
                    "ReportedByEmployee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_bugs",
                        to="bughoundapp.employee",
                    ),
                ),
                (
                    "ResolvedByEmployee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_bugs",
                        to="bughoundapp.employee",
                    ),
                ),
                (
                    "TestedByEmployee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tested_bugs",
                        to="bughoundapp.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FileType", models.CharField(max_length=255)),
                ("FilePath", models.TextField()),
                (
                    "BugReportNumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bughoundapp.bugreport",
                    ),
                ),
            ],
        ),
    ]
